# Generated by Django 4.2.23 on 2025-08-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_count',
            new_name='book_available_count',
        ),
    ]
