# Generated by Django 4.2.23 on 2025-08-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookgenre_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
