# Generated by Django 4.2.23 on 2025-08-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_available_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='available_count',
            new_name='number_of_copies',
        ),
    ]
