# Generated by Django 4.2.23 on 2025-08-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='date_borrowed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
