# Generated by Django 4.2.23 on 2025-08-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookinstance_date_borrowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
    ]
