# Generated by Django 4.2.23 on 2025-08-13 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookinstance_is_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='date_borrowed',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 3, 44, 53, 551649, tzinfo=datetime.timezone.utc)),
        ),
    ]
