# Generated by Django 4.2.23 on 2025-08-13 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_bookinstance_date_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='date_borrowed',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 3, 47, 48, 389884, tzinfo=datetime.timezone.utc)),
        ),
    ]
