# Generated by Django 4.2.23 on 2025-08-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_bookinstance_date_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='date_borrowed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
