# Generated by Django 4.2.23 on 2025-08-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_bookinstance_date_borrowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(default='default_cover.jpg', upload_to=''),
        ),
    ]
