# Generated by Django 4.2.23 on 2025-08-06 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='books.bookinstance')),
            ],
        ),
    ]
