# Generated by Django 4.2.23 on 2025-08-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
