# Generated by Django 4.2.23 on 2025-08-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_borrow_date_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='fees_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='borrow',
            name='fees_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrow',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
