# Generated by Django 4.2.23 on 2025-08-13 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_borrow_fees_amount_borrow_fees_paid_borrow_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='date_borrowed',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 3, 44, 53, 552084, tzinfo=datetime.timezone.utc)),
        ),
    ]
