# Generated by Django 4.2.23 on 2025-08-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0004_alter_borrow_date_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='date_borrowed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
